### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by mcagabe19** [Square789/PydayNightFunkin#48]
did all things at readme gotting this:

![16789709945803389570633899946336](https://user-images.githubusercontent.com/82843871/225622083-294084a8-e604-42df-969b-46acd4d22c4f.jpg)

**Comment by Square789** [comment]
That probably means the`setup.py build_ext -i` command failed. Could you provide its output?

**Comment by mcagabe19** [comment]
nvm fixed
